### PR TITLE
update rspec to 3.5 so that shit doesnt break

### PR DESCRIPTION
**Pull request by josephwegner**
Hopefully this fixes our CI errors

### CODE REVIEW

**Comment by dkador** [comment]
i don't mind the rspec change but why would the error type change?

**Comment by josephwegner** [comment]
@dan I don't actually know why... but it did :D I can look into it more

**Comment by josephwegner** [comment]
but, anyways, not all of the specs are passing, so this doesn't work anyways

**Comment by dkador** [comment]
ok, holler at me once you have something else you'd like me to look at.

**Pull request merged**
