### PR TITLE
Move SavedQueries to the Keen:: namespace

### PR DESCRIPTION
**Pull request by myrridin**
SavedQueries did not follow naming conventions elsewhere in the gem, and could cause name collisions. It has been moved out of the Client namespace into the base Keen namespace, and properly wrapped in the Keen module

This addresses https://github.com/keenlabs/keen-gem/issues/92

### CODE REVIEW

**Comment by josephwegner** [comment]
Looks like there were some CI issues. I just fixed theses in #100. Can you merge master in and see if CI passes then?

**Comment by josephwegner** [comment]
Hi @myrridin!

I'm going to close this for now. If you'd like to revisit it and merge in master, I'd be happy to review and get it merged then.

**Comment by myrridin** [comment]
I knew there was something I was meaning to do. Sorry for the delay @josephwegner. I will definitely reissue these PRs with master merged.

**Comment by myrridin** [comment]
Hey @josephwegner these 4 PRs have been reissued after merging in master. Please let me know if there's anything else I can do.

**Pull request closed without merging**
